# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v4.2.2        

    - name: Set up Go
      uses: actions/setup-go@v5.5.0
      with:
        go-version-file: go.mod

    - name: Build Linux amd64
      run: |
        go env -w GOOS=linux
        go env -w GOARCH=amd64
        go env
        go build -ldflags="-s -w" -trimpath -v -o xddns-linux-amd64 .

    - name: Build Linux arm64
      run: |
        go env -w GOOS=linux
        go env -w GOARCH=arm64
        go env
        go build -ldflags="-s -w" -trimpath -v -o xddns-linux-arm64 .

    
    - name: Build windows
      run: |
        go env -w GOOS=windows
        go env -w GOARCH=amd64
        go env
        go build -ldflags="-s -w" -trimpath -v -o xddns-windows-amd64.exe .

    - name: Dump Files
      run: |
        ls -lah

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        name: "Build - ${{ github.sha }}"
        tagName: ${{ github.sha }}
